/**
 * Created by cam on 12/6/2015.
 */
module.exports = {
    building_type: [ { col: 'Academic/Administrative' },
        { col: 'Dining' },
        { col: 'Housing' },
        { col: 'Parking' },
        { col: 'Medical' },
        { col: 'Library' },
        { col: 'Store' } ],
    crime_type: [ { col: 'Moving Violation' },
        { col: 'Robbery' },
        { col: 'Theft' },
        { col: 'Underage Possession of Alcohol' },
        { col: 'Resist/Delay/Obstruction of justice' },
        { col: 'Sexual assault' },
        { col: 'Injury to personal property' },
        { col: 'Forgery and Uttering' },
        { col: 'Trespassing' },
        { col: 'Stalking' },
        { col: 'Assault' },
        { col: 'Drug Possession' },
        { col: 'Burglary' },
        { col: 'Arson' },
        { col: 'Breaking and Entering' },
        { col: 'Weapon Possession' },
        { col: 'Alcohol violation' },
        { col: 'Armed Robbery' },
        { col: 'Fraud' },
        { col: 'Larceny' },
        { col: 'Indecent exposure' },
        { col: 'Driving while Intoxicated' } ],
    building_name: [ { col: '1700 Pace' },
        { col: '1706 Pace' },
        { col: '1708 Pace' },
        { col: '1712 Pace' },
        { col: '1809 Erwin' },
        { col: '1901 Erwin' },
        { col: '1905 Erwin' },
        { col: '1907 Erwin' },
        { col: '1909 Erwin' },
        { col: '1909 Yearby' },
        { col: '1911 Erwin' },
        { col: '1911 Yearby' },
        { col: '1913 Erwin' },
        { col: '1914 Lewis' },
        { col: '1915 Erwin' },
        { col: '1915 Yearby' },
        { col: '201 Alexander' },
        { col: '2011 Yearby' },
        { col: '2015 Yearby' },
        { col: '2017 Yearby' },
        { col: '202 Alexander' },
        { col: '2022 Campus Drive' },
        { col: '204 Alexander' },
        { col: '205 Alexander' },
        { col: '205 Oregon' },
        { col: '206 Alexander' },
        { col: '206 Oregon' },
        { col: '208 Alexander' },
        { col: '209 Alexander' },
        { col: '209 Anderson' },
        { col: '210 Alexander' },
        { col: '215 Alexander' },
        { col: '215 Anderson' },
        { col: '218 Alexander' },
        { col: '220 Alexander' },
        { col: '221 Anderson' },
        { col: '301 Oregon' },
        { col: '301 Swift' },
        { col: '302 Anderson' },
        { col: '302 Oregon' },
        { col: '304 Anderson' },
        { col: '312 Anderson' },
        { col: '314 Anderson' },
        { col: '705 Broad St' },
        { col: 'Allen Building' },
        { col: 'Allen Lot' },
        { col: 'Alspaugh Residence Hall' },
        { col: 'Art Building' },
        { col: 'Au Bon Pain' },
        { col: 'Basset Residence Hall' },
        { col: 'Bell Tower Residence Hall' },
        { col: 'Bella Union' },
        { col: 'Bevan Building' },
        { col: 'Biddle Music Building' },
        { col: 'Biddle Music Lot' },
        { col: 'Biological Sciences Building' },
        { col: 'Biological Sciences Greenhouses' },
        { col: 'Bivans Building' },
        { col: 'Blackwell Residence Hall' },
        { col: 'Blue Express' },
        { col: 'Blue Zone Lot' },
        { col: 'Bostock Library' },
        { col: 'Brian Center Lot' },
        { col: 'Brian Center Parking Garage' },
        { col: 'Brown Lot' },
        { col: 'Brown Residence Hall' },
        { col: 'Bryan Center Lobby Shop' },
        { col: 'Cafe at Smith Warehouse' },
        { col: 'Carr Building' },
        { col: 'Center for Documentary Studies' },
        { col: 'Center for Muslim Life' },
        { col: 'Central Housing Lot 1' },
        { col: 'Central Housing Lot 2' },
        { col: 'Central Housing Lot 3' },
        { col: 'Childcare Facility' },
        { col: 'Craven House A' },
        { col: 'Craven House AA' },
        { col: 'Craven House B' },
        { col: 'Craven House C' },
        { col: 'Craven House D' },
        { col: 'Craven House E' },
        { col: 'Craven House F' },
        { col: 'Craven House R' },
        { col: 'Craven House S' },
        { col: 'Craven House T' },
        { col: 'Craven House U' },
        { col: 'Craven House V0 & v00' },
        { col: 'Craven House W/Y' },
        { col: 'Craven House X' },
        { col: 'Craven House Z' },
        { col: 'Crowell Building' },
        { col: 'Crowell House BB' },
        { col: 'Crowell House CC' },
        { col: 'Crowell House DD' },
        { col: 'Crowell House EE' },
        { col: 'Crowell House G' },
        { col: 'Crowell House H' },
        { col: 'Davidson Building' },
        { col: 'Devil\'s Bistro' },
        { col: 'Devil\'s Den' },
        { col: 'Divinity Cafe' },
        { col: 'Divinity School' },
        { col: 'Dolce Vita' },
        { col: 'Doris Duke Center' },
        { col: 'Duke Children\'s Hospital' },
        { col: 'Duke Hospital' },
        { col: 'Duke Police Lot' },
        { col: 'Duke Student Health' },
        { col: 'Duke VA Medical Center' },
        { col: 'East Campus Store' },
        { col: 'East Duke Building' },
        { col: 'East Residence Hall' },
        { col: 'Edens B Lot' },
        { col: 'Edens C Lot' },
        { col: 'Edens D Lot' },
        { col: 'Edens House 1A' },
        { col: 'Edens House 1B' },
        { col: 'Edens House 1C' },
        { col: 'Edens House 2A' },
        { col: 'Edens House 2C' },
        { col: 'Edens House 3A (Decker Tower)' },
        { col: 'Edens House 3B (Mitchell Tower)' },
        { col: 'Environment Hall' },
        { col: 'Episcopal Center' },
        { col: 'Epworth Lot' },
        { col: 'Epworth Residence Hall' },
        { col: 'Faculty Club' },
        { col: 'Few House FF' },
        { col: 'Few House GG' },
        { col: 'Few House HH' },
        { col: 'Fitzpatrick Center for Interdisciplinary Engineering, Medicine, and Applied Sciences' },
        { col: 'Flowers Building' },
        { col: 'Freeman Center' },
        { col: 'Freeman Center for Jewish Life' },
        { col: 'French Family Science Center' },
        { col: 'Friedl Building' },
        { col: 'Fuqua School of Business' },
        { col: 'Gilbert-Addoms Residence Hall' },
        { col: 'Giles Residence Hall' },
        { col: 'Global Health Research Building' },
        { col: 'Goodson Law Library' },
        { col: 'Gothic Bookshop' },
        { col: 'Grace\'s Cafe' },
        { col: 'Gross Hall' },
        { col: 'H Lot' },
        { col: 'Hart House' },
        { col: 'Hudson Hall Engineering Building' },
        { col: 'IM Lot' },
        { col: 'International House' },
        { col: 'Jarvis Residence Hall' },
        { col: 'Joe Van Gogh' },
        { col: 'Keohane House 4A' },
        { col: 'Keohane House 4B' },
        { col: 'Keohane House 4D' },
        { col: 'Keohane House 4E' },
        { col: 'Kilgo House I' },
        { col: 'Kilgo House J' },
        { col: 'Kilgo House K' },
        { col: 'Kilgo House L' },
        { col: 'Kilgo House M' },
        { col: 'Kilgo House N' },
        { col: 'Kilgo House O' },
        { col: 'Kilgo House P' },
        { col: 'Languages Building' },
        { col: 'Law School Building' },
        { col: 'Law School Lot' },
        { col: 'Levine Science Research Center' },
        { col: 'Lilly Library' },
        { col: 'Marketplace' },
        { col: 'Marketplace (East Campus Union)' },
        { col: 'McDonald\'s' },
        { col: 'Mill Village' },
        { col: 'NOSH' },
        { col: 'Nasher Museum Cafe' },
        { col: 'Nicholas Institute' },
        { col: 'North Building' },
        { col: 'OIT-Telecommunications Building' },
        { col: 'Old Chemistry Building' },
        { col: 'Panda Express' },
        { col: 'Pegram Residence Hall' },
        { col: 'Penn Pavillion' },
        { col: 'Perkins Library' },
        { col: 'Physics Building' },
        { col: 'Pitchfork Provisions' },
        { col: 'Public Policy Lot' },
        { col: 'Quenchers' },
        { col: 'Randolph Residence Hall' },
        { col: 'Red Mango' },
        { col: 'Rubenstein Rare Books Library' },
        { col: 'Saladelia Cafe @ Sanford' },
        { col: 'Saladelia at the Perk' },
        { col: 'Sanford School of Public Policy' },
        { col: 'School of Nursing' },
        { col: 'Smith Warehouse' },
        { col: 'Smith Warehouse Lot N' },
        { col: 'Smith Warehouse Lot S' },
        { col: 'Snyderman Genome Science Research Building' },
        { col: 'Social Sciences Building' },
        { col: 'Sociology-Psychology' },
        { col: 'Southgate Lot' },
        { col: 'Southgate Residence Hall' },
        { col: 'Student Health Center' },
        { col: 'Teer Building' },
        { col: 'Terrace Cafe' },
        { col: 'The Plaza' },
        { col: 'Trent Drive Hall' },
        { col: 'Trinity Cafe' },
        { col: 'Twinnie\'s' },
        { col: 'Undergraduate Admissions' },
        { col: 'Wannamaker 1' },
        { col: 'Wannamaker 2' },
        { col: 'Wannamaker 3' },
        { col: 'Wannamaker 4' },
        { col: 'West Duke Building' },
        { col: 'White Lecture Hall' },
        { col: 'Wilson Lot' },
        { col: 'Wilson Residence Hall' } ],
    building_campus: [ { col: 'West' }, { col: 'Central' }, { col: 'East' } ],
    crime_exterior: [ { col: 'outside' }, { col: 'inside' } ],
    crime_disposition: [ { col: 'Closed' },
        { col: 'Closed-SC' },
        { col: 'Exceptionally Cleared' },
        { col: 'Unfounded' },
        { col: 'Pending' },
        { col: 'Arrest' },
        { col: 'Cleared by Referral' } ],
    crime_tags: [ { col: 'driving' },
        { col: 'theft, etc.' },
        { col: 'alcohol/drugs' },
        { col: 'other' },
        { col: 'violent,sex-related' },
        { col: 'violent' },
        { col: 'trespassing, etc.' },
        { col: 'sex-related' },
        { col: 'violent,theft, etc.' },
        { col: 'driving,alcohol/drugs' } ]
}